[ST-27] Event Interactivity
sandboxnu/sga-tooling pull request #17
Opened 2022-12-04 21:10 UTC by banushi-a

• Register button is now interactive

• Dropdown menu:

<img width="250" alt="Screen Shot 2022-12-04 at 4 09 26 PM" src="https://user-images.githubusercontent.com/89368127/205515752-96c6a348-6b14-4979-927d-ed4bdc284e5d.png">

2022-12-09 03:21 UTC, chanmioh reviewed
Looks good, I would recommend also implementing a way to close that event settings pop-up   by clicking outside of it as you might see on some sites! Here's a link to the instructions, lmk if you can get it working, if not we can likely make a new ticket for this: https://blog.logrocket.com/detect-click-outside-react-component-how-to/

Lmk if u have any questions!

2022-12-09 03:21 UTC, chanmioh commented on src/components/EventCard.tsx
> +  let regButtonStyle = regStatus ? "button-base-white px-2 my-2 mr-5" : "button-base-red px-2 my-2 mr-5";
I'd add more padding to the button when it's red so that it doesn't look too jarring when it's switched between Unregister and Register!

```suggestion
  let regButtonStyle = regStatus ? "button-base-white px-2 my-2 mr-5" : "button-base-red px-4 my-2 mr-5";
```

2022-12-09 03:21 UTC, chanmioh commented on src/components/EventCard.tsx
> +  let [regStatus, setRegStatus] = useState(true);
I'd rename this to something more readable like `isRegistered` and `setIsRegistered`, or you can also just leave a comment explaining what "reg status" means

2022-12-09 03:21 UTC, chanmioh commented on src/components/EventCard.tsx
> +            <details className="relative">
Really like the inclusion of semantic elements! Makes the code a lot more readable when distinguishing element types from just `div`

2022-12-09 03:21 UTC, chanmioh commented on src/components/EventCard.tsx
> +              <div className="absolute -ml-40 drop-shadow-[0_12px_12px_rgba(0,0,0,0.4)] rounded-xl bg-white">
Would it be possible to use one of the predefined `drop-shadow` styles, to keep shadow colors consistent?

2022-12-11 02:48 UTC, melocule requested changes, later dismissed

2022-12-11 02:48 UTC, melocule commented on src/components/EventCard.tsx
> +  let regButtonStyle = regStatus ? "button-base-white px-2 my-2 mr-5" : "button-base-red px-2 my-2 mr-5";
Fixed width button? Would look nicer

2022-12-11 03:47 UTC, chanmioh commented on src/components/EventCard.tsx
> +  let [isRegistered, setisRegistered] = useState(true);
I'd recommend using a `const` here unless the variable will change, because this will enforce the variable to stay constant

2022-12-11 03:47 UTC, chanmioh commented on src/components/EventCard.tsx
> +  let regButtonStyle = isRegistered ? "button-base-white px-3 my-2 mr-5 w-32" : "button-base-red px-4 my-2 mr-5 w-32";
Same here as well, I recommend using `const`

2022-12-11 03:47 UTC, chanmioh commented on tailwind.config.js
> +        'cooper': "url(/src/assets/login-page-cooper.jpg)",
Do we need the `url()` here? Otherwise I'd recommend excluding

2022-12-11 03:47 UTC, chanmioh commented on src/components/EventCard.tsx
> +              <div className="absolute -ml-40 drop-shadow-[0_12px_12px_rgba(0,0,0,0.3)] rounded-xl bg-white">
Make sure to include your new drop-down preset from `tailwind-config`

2022-12-11 03:47 UTC, chanmioh commented on src/components/EventCard.tsx
> +                <button className="button-base-red px-4 my-2">See More</button>
Can we also make the `See more` button the same size as the `Unregister` button for consistency? (Can also ask the designer aka jawsh)

2022-12-11 03:47 UTC, chanmioh commented on src/components/EventCard.tsx
> +  let [isRegistered, setisRegistered] = useState(true);
Also would name this `setIsRegistered`

2022-12-11 04:11 UTC, chanmioh approved these changes
lgtm ❇️

2022-12-11 04:15 UTC, merged